Checkpoint rage control
SirPlease/L4D2-Competitive-Rework pull request #795
Opened 2024-07-29 01:32 UTC by lechuga16

- Fixed a bug, when a survivor enters a team, the announcement is displayed.
- Rearranged the code to make it simpler to review.
- `Event_RoundEndEvent `was replaced by `L4D2_OnEndVersusModeRound_Post`.
- Updated the syntax

Note: I made these changes in order to identify the '`if (LoadFromAddress(pTarget, NumberType_Int8) != CALL_OPCODE)`' error. although I can't figure out how to fix it.

2024-07-29 02:33 UTC, nikita1824 commented
Hello, we faced `if (LoadFromAddress(pTarget, NumberType_Int8) != CALL_OPCODE)` scenario and this is probably left4dhooks unloads before checkpoint-rage-control. 
Try to disable requirement of left4dhooks.

2024-08-13 00:05 UTC, SirPlease requested changes
Just clear up the few typos/mistakes and it should be good to go 👍

2024-08-13 00:05 UTC, SirPlease commented on addons/sourcemod/scripting/checkpoint-rage-control.sp
> +	DebugPrint("{blue}Prepared hooks{default} from L4D_OnSpawnTank_Post [player_entered_start_area, player_death]");
Oi, `player_team` is also being hooked! 😛

2024-08-13 20:56 UTC, lechuga16 commented
@SirPlease done.

2024-08-15 13:41 UTC, merged